spring:
  datasource:
    url: jdbc:postgresql://dpg-d8f0u6i8qa3s738f8sig-a.oregon-postgres.render.com:5432/sitedados?sslmode=require
    username: admin
    password: UdW6H4XTUZe0YkoablwfuxpJiu9D9YUZ
    driverClassName: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgres.sql